volumes:
  log-files:
    - .
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel/otel.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 9091:9091 # prometheus exporter
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  tempo:
    image: grafana/tempo
    command:
      - "--config.file=/etc/tempo.yaml"
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200"
      - "4317"
  loki:
    image: grafana/loki
    command:
      - "--config.file=/etc/loki.yaml"
    volumes:
      - ./loki/loki.yaml:/etc/loki.yaml
    ports:
      - "3100"
      - "9096"
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasource.yml
